apps/tickets_ua/urls.py
from django.urls import path

from apps.tickets_ua.views import api
from apps.tickets_ua.views.checker import CheckerListView

app_name = "tickets_ua"
urlpatterns = [
    path("", CheckerListView.as_view(), name="index"),

    path("api/station/", api.StationCreateAPIView.as_view(), name="api-station"),
    path("api/checker/", api.CheckerCreateAPIView.as_view(), name="api-checker"),
    path("api/checker/<int:pk>/", api.CheckerUpdateAPIView.as_view(), name='api-update-checker'),
]

apps/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.views import index, telegram, feedback, redirect_to_index_page, additional_settings, change_max_query_number, \
    change_vip_users_update_period, change_regular_users_update_period

urlpatterns = [
    path("", index, name="index"),
    path("", include('apps.tbot_base.urls')),  # include webhook url
    path("telegram/", telegram, name="telegram"),
    path("feedback/", feedback, name="feedback"),
    path("settings/", additional_settings, name="settings"),
    path("change_max_query_number/", change_max_query_number, name="change_max_query_number"),
    path("change_regular_users_update_period/", change_regular_users_update_period,
         name="change_regular_users_update_period"),
    path("change_vip_users_update_period/", change_vip_users_update_period, name="change_vip_users_update_period"),

    path('i18n/', include('django.conf.urls.i18n')),

    path("uz_ticket/", include('apps.uz_ticket_checker.urls'), name="uz_ticket_checker"),
    path("tickets_ua/", include('apps.tickets_ua.urls'), name="tickets_ua"),
    path("hotline_ua/", include('apps.hotline_ua.urls'), name="hotline_ua"),

    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('apps.accounts.urls'), name="accounts"),

    path('oauth2/inactive/', redirect_to_index_page),
    path('oauth2/', include('allauth.urls')),
    # path('oauth2/', include('allauth.socialaccount.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

apps/uz_ticket_checker/urls.py
from django.urls import path

from apps.uz_ticket_checker.views.checker_view import checker_add, checkers_view, checker_delete, \
    checker_change_is_active
from apps.uz_ticket_checker.views.stations_view import StationsListView, stations_update
from apps.uz_ticket_checker.views.ticket_search_view import search_ticket_view, get_search_results

app_name = "uz_ticket_checker_app"
urlpatterns = [
    path("", search_ticket_view, name="search_results"),
    path("execute_search_task/", get_search_results, name="execute_task"),
    path("checker/", checkers_view, name="checker"),
    path("checker/add/", checker_add, name="checker_add"),
    path("checker/delete/<int:pk>/", checker_delete, name="checker_delete"),
    path("checker/change_is_active/<int:pk>/", checker_change_is_active, name="checker_change_is_active"),
    path("stations/", StationsListView.as_view(), name="stations"),
    path("stations/update/", stations_update, name="stations_update"),
]

apps/uz_ticket_checker/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from loguru import logger

from apps.common import TimeStampedMixin
from apps.accounts.models import BaseParameter
from apps.common.constants import SEAT_TYPES, WAGON_TYPES, STATIONS


class Station(TimeStampedMixin):
    express_3_id = models.BigAutoField(
        auto_created=True,
        primary_key=True,
        serialize=False,
        verbose_name=_("EXPRESS-3 ID")
    )
    name = models.CharField(_("station name"), max_length=150)
    country = models.ForeignKey(
        "Country",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name=_("country"),
        verbose_name=_("country"))
    weight = models.DecimalField(max_digits=4, decimal_places=1, verbose_name=_("weight"))
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active."
            "Unselect this instead of deleting accounts."
        ),
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("station")
        verbose_name_plural = _("stations")


class Country(models.Model):
    name = models.CharField(_("country name"), max_length=150)


class TicketSearchParameter(BaseParameter):
    departure_station = models.ForeignKey(
        "Station",
        on_delete=models.CASCADE,
        null=False,
        related_name=_("departures"),
        verbose_name=_("departure station"))
    arrival_station = models.ForeignKey(
        "Station",
        on_delete=models.CASCADE,
        null=False,
        related_name=_("arrivals"),
        verbose_name=_("arrival station"))
    start_date = models.DateTimeField(_("start date"), null=False)
    end_date = models.DateTimeField(_("end date"), null=False)
    train_number = models.ManyToManyField("TrainNumber", related_name="train_numbers")
    wagon_type = models.ManyToManyField("WagonType", related_name="wagon_types")
    seat_type = models.ManyToManyField("SeatType", related_name="seat_types")


class TrainNumber(models.Model):
    train_number = models.CharField(_("train number"), max_length=50)


class WagonType(models.Model):
    wagon_type = models.CharField(_("wagon type"), max_length=50)


class SeatType(models.Model):
    seat_type = models.CharField(_("seat type"), max_length=50)
    seat_type_name = models.CharField(_("seat type name"), max_length=50)


# Get active stations info for using in checkers app
try:
    if Station.objects.filter(is_active=True).exists():
        stations = Station.objects.filter(is_active=True).order_by('-weight')
        for station in stations:
            STATIONS[station.express_3_id] = station.name
except Exception as e:
    logger.info(e)


# wagon types initializing
try:
    for wagon_type in WAGON_TYPES:
        if not WagonType.objects.filter(wagon_type=wagon_type).exists():
            wagon_type_obj = WagonType(wagon_type=wagon_type)
            wagon_type_obj.save()
except Exception as e:
    logger.info(e)


# Update wagon types from DB for using in checkers app
try:
    if WagonType.objects.exists():
        wagon_types = WagonType.objects.all()
        WAGON_TYPES.clear()
        for wagon_type in wagon_types:
            WAGON_TYPES.append(wagon_type.wagon_type)
except Exception as e:
    logger.info(e)


# seat types initializing
try:
    for seat_type in SEAT_TYPES:
        if not SeatType.objects.filter(seat_type=seat_type['seat_type']).exists():
            seat_type_obj = SeatType(seat_type=seat_type['seat_type'], seat_type_name=seat_type['seat_type_name'])
            seat_type_obj.save()
except Exception as e:
    logger.info(e)


# Update seat types from DB for using in checkers app
try:
    if SeatType.objects.exists():
        seat_types = SeatType.objects.all()
        SEAT_TYPES.clear()
        for seat_type in seat_types:
            SEAT_TYPES.append({'seat_type': seat_type.seat_type, 'seat_type_name': seat_type.seat_type_name})
except Exception as e:
    logger.info(e)

apps/booking_uz_gov_ua/views/checker.py
from django.contrib import messages
from django.shortcuts import redirect, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic.list import ListView

from apps.booking_uz_gov_ua.models import Checker


class CheckerListView(ListView):
    template_name = 'booking_uz_gov_ua/index.html'
    context_object_name = 'checkers'

    def get_queryset(self):
        user = self.request.user
        if not user.is_authenticated:
            return []

        queryset = Checker.objects.filter(user_id=user.id)
        return queryset

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            messages.warning(self.request, _('Unauthorized access. Please log in.'))
            return redirect(reverse('index'))

        return super().get(request, *args, **kwargs)

apps/hotline_ua/views/checker.py
from django.views.generic import ListView

from apps.common.views import BaseCheckerListView
from apps.common.enums.checker_name import CheckerTypeName
from apps.hotline_ua.models import BaseSearchParameter


class CheckerListView(BaseCheckerListView, ListView):
    model_class = BaseSearchParameter
    template_name = 'hotline_ua/index.html'
    context_object_name = 'checkers'
    checker_type = CheckerTypeName.HOTLINE_UA

apps/tickets_ua/views/checker.py
from django.views.generic import ListView

from apps.common.views import BaseCheckerListView
from apps.common.enums.checker_name import CheckerTypeName
from apps.tickets_ua.enums.seat import SeatType
from apps.tickets_ua.models import BaseSearchParameter


class CheckerListView(BaseCheckerListView, ListView):
    model_class = BaseSearchParameter
    template_name = 'tickets_ua/index.html'
    context_object_name = 'checkers'
    checker_type = CheckerTypeName.TICKETS_UA

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seat_types'] = [i.name.replace('_', ' ').lower() for i in SeatType if i != SeatType.DEFAULT]
        return context

apps/uz_ticket_checker/views/checker_view.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from loguru import logger

from apps.accounts.utils.telegram import has_user_related_telegram_id
from apps.common.constants import STATIONS, WAGON_TYPES, SEAT_TYPES
from apps.task_manager.models import CheckerTask, SessionTaskManager
from apps.tbot.handlers.send_uz_tickets_matches import send_tickets
from apps.uz_ticket_checker.models import TicketSearchParameter
from apps.uz_ticket_checker.services.checker_service import add_new_checker, get_checkers_parameters_list_for_frontend, \
    get_direction_info_str, get_checker_matches, get_checker_matches_info_dict


def checkers_view(request):
    if request.user and not request.user.is_authenticated:
        messages.info(request, 'Доступ до сторінки списку чекерів мають лише авторизовані користувачі.')
        return redirect(reverse('uz_ticket_checker_app:search_results'))
    if not has_user_related_telegram_id(request):
        return redirect(reverse('telegram'))

    context = {}
    user = request.user
    context['parameters'] = get_checkers_parameters_list_for_frontend(user)
    context['stations'] = STATIONS
    context['wagon_types'] = WAGON_TYPES
    context['seat_types'] = SEAT_TYPES

    if request.method == 'GET':
        context['from_station'] = int(request.GET.get('from_station', 2200001))
        context['to_station'] = int(request.GET.get('to_station', 2218000))
        if request.GET.get('train_number'):
            context['train_number'] = request.GET.get('train_number')
        if request.GET.get('wagon_type'):
            context['selected_wagon_types'] = request.GET.get('wagon_type')
        if request.GET.get('from_date'):
            from_date = request.GET.get('from_date')
            context['from_date'] = from_date
            context['to_date'] = request.GET.get('to_date', from_date)

    if request.method == 'POST':
        context['from_station'] = request.POST.get('from_station', 2200001)
        context['to_station'] = request.POST.get('to_station', 2218000)
        context['train_number'] = request.POST.get('to_station', 2218000)
        context['selected_wagon_types'] = []
        context['selected_seat_types'] = []
        if request.POST.get('from_date'):
            from_date = request.POST.get('from_date')
            context['from_date'] = from_date
            context['to_date'] = request.POST.get('to_date', from_date)

    SessionTaskManager(request)
    return render(request, 'uz_ticket_checker/checker.html', context)


def checker_add(request):
    if request.user and not request.user.is_authenticated:
        previous_page = request.META.get('HTTP_REFERER', '/')
        return HttpResponseRedirect(previous_page)

    user = request.user
    if not CheckerTask.objects.can_create_new_task(user.pk):
        messages.info(request, 'Кількість вільних для використання чекерів закінчилася.')
    elif request.method == 'POST':
        departure_station_str = request.POST.get('from_station')
        arrival_station_str = request.POST.get('to_station')
        trip_dates = request.POST.get('trip_dates').split(" - ")
        start_date_str = trip_dates[0]
        end_date_str = trip_dates[1]
        train_numbers = request.POST.get('train_numbers').split(",")
        wagon_types = request.POST.getlist('wagon_types')
        seat_types = request.POST.getlist('seat_types')

        try:
            add_new_checker(
                user,
                departure_station_str,
                arrival_station_str,
                start_date_str,
                end_date_str,
                train_numbers,
                wagon_types,
                seat_types
            )
            SessionTaskManager(request)
        except Exception as e:
            logger.error(e)
    return redirect(reverse('uz_ticket_checker_app:checker'))


def checker_delete(request, pk):
    if request.user and not request.user.is_authenticated:
        previous_page = request.META.get('HTTP_REFERER', '/')
        return HttpResponseRedirect(previous_page)

    delete_object = get_object_or_404(CheckerTask, pk=pk)
    if request.method == 'GET':
        delete_object.is_delete = True
        delete_object.save()
        SessionTaskManager(request)
    return redirect(reverse('uz_ticket_checker_app:checker'))


def checker_change_is_active(request, pk):
    if request.user and not request.user.is_authenticated:
        previous_page = request.META.get('HTTP_REFERER', '/')
        return HttpResponseRedirect(previous_page)

    change_object = get_object_or_404(CheckerTask, pk=pk)
    if request.method == 'POST':
        is_active = change_object.is_active
        change_object.is_active = not is_active
        change_object.save()
    return redirect(reverse('uz_ticket_checker_app:checker'))

apps/uz_ticket_checker/views/stations_update.py
from django.shortcuts import render

from apps.uz_ticket_checker.services.stations_update_service import run_all_stations_update


def stations_update(request):
    # if request.user and not request.user.is_superuser:
    #     messages.error(request, 'Доступ до сторінки додавання нових продуктів мають лише суперюзери.')
    #     return redirect(reverse('products:products_list'))

    if request.method == 'GET':
        run_all_stations_update()
    return render(request, 'uz_ticket_checker/stations.html')

apps/uz_ticket_checker/views/stations_view.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.list import ListView

from apps.common.constants import UKRAINIAN_ALPHABET
from apps.uz_ticket_checker.models import Station


class StationsListView(ListView):
    model = Station
    template_name = 'uz_ticket_checker/stations.html'
    context_object_name = 'stations'
    paginate_by = 300

    def dispatch(self, request, *args, **kwargs):
        if request.user and not request.user.is_superuser:
            messages.info(request,
                          'Доступ до сторінки списку станцій сервісу "UZ tickets Search" мають лише суперюзери.')
            return redirect(reverse('uz_ticket_checker_app:search_results'))
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Station.objects.filter(is_active=1).order_by('-weight')


def stations_update(request, run_stations_scraping_task=None):
    if request.user and not request.user.is_superuser:
        messages.info(request, 'Доступ до оновлення станцій сервісу "UZ tickets Search" мають лише суперюзери.')
        return redirect(reverse('uz_ticket_checker_app:search_results'))

    if request.method == 'GET':
        for letter in UKRAINIAN_ALPHABET:
            run_stations_scraping_task.delay(phrase=letter)
    return render(request, 'uz_ticket_checker/stations.html')

apps/uz_ticket_checker/views/ticket_search_view.py
import json

from celery.result import AsyncResult
from django.http import JsonResponse
from django.shortcuts import render
from loguru import logger

from apps.common.constants import STATIONS
from apps.task_manager.models import SessionTaskManager
from apps.uz_ticket_checker.tasks import run_tickets_search_task


def search_ticket_view(request):
    context = {}
    if request.method == 'GET':
        context['stations'] = STATIONS
    SessionTaskManager(request)
    return render(request, 'uz_ticket_checker/ticket_search_page.html', context)


def get_search_results(request):
    task_result = []
    if request.method == 'POST':
        from_station = request.POST.get('from_station')
        to_station = request.POST.get('to_station')
        from_date = request.POST.get('from_date')
        to_date = request.POST.get('to_date', from_date)

        try:
            final_result = run_tickets_search_task.delay(from_station=from_station, to_station=to_station,
                                                         from_date=from_date, to_date=to_date)
            task_id = final_result.id
            async_result = AsyncResult(task_id)
            task_result = async_result.get()
        except Exception as e:
            logger.debug(e)
    return JsonResponse(json.dumps(task_result), safe=False)

templates/uz_ticket_checker/stations.html
{% extends 'fragments/base.html' %}
{% load static %}

{% block main %}
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="my-3 p-3 bg-body rounded shadow-sm">
                <h3 class="pb-2" align="center">Список станцій доступних в додатку</h3>
                <div class="bg-body rounded shadow-sm">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th class="col-auto text-primary-emphasis border">EXPRESS-3 ID</th>
                                <th class="col-auto text-primary-emphasis border">Назва станції</th>
                                <th class="col-auto text-primary-emphasis border">Вагомість</th>
                            </tr>
                        </thead>
                    
                        <tbody class="text-center" id="checkersBodyTable">
                        {% for station in stations %}
                            <tr>
                                <td>{{ station.express_3_id }}</td>
                                <td>{{ station.name }}</td>
                                <td>{{ station.weight }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            
                <br><br>
                <table class="table">
                    <thead>
                        <tr class="text-center">
                            <th class="col-auto text-primary-emphasis">
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; перша</a>
                                    <span style="margin-right: 12px;"></span>
                                    <a href="?page={{ page_obj.previous_page_number }}">&laquo; попередня</a>
                                    <span style="margin-right: 12px;"></span>
                                {% endif %}
                            
                                <span class="current">
                                    Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}.
                                </span>
                            
                                {% if page_obj.has_next %}
                                    <span style="margin-right: 12px;"></span>
                                    <a href="?page={{ page_obj.next_page_number }}">наступна &raquo;</a>
                                    <span style="margin-right: 12px;"></span>
                                    <a href="?page={{ page_obj.paginator.num_pages }}">остання &raquo;</a>
                                {% endif %}
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        
{#        <script>#}
{#            window.StationUrl = "{% url 'tickets_ua:api-station' %}"#}
{#            window.ChekerUrl = "{% url 'tickets_ua:api-checker' %}"#}
{#        </script>#}

{#        <script>#}
{#            $('#range-time').on('input', function () {#}
{#                const time = $('#range-time').val()#}
{#                $('#range-time-value').val((time < 10 ? "0" + time : time) + ":00")#}
{#            });#}
{#        </script>#}

{#        <script src="{% static '/js/moment.min.js' %}"></script>#}
{#        <script src="{% static '/js/daterangepicker.js' %}"></script>#}
{#        <script>#}
{#            $(function () {#}
{#                $('input[name="date_at"]').daterangepicker({#}
{#                    opens: 'left',#}
{#                    startDate: moment(),#}
{#                    minDate: moment(),#}
{#                    endDate: moment(),#}
{#                    maxDate: moment().add(10, 'day'),#}
{#                    locale: {#}
{#                        format: 'YYYY-MM-DD'#}
{#                    }#}
{#                });#}
{#            });#}
{#        </script>#}

{#        <script src="{% static '/js/calc.js' %}"></script>#}
{#        <script src="{% static '/js/ajax.js' %}"></script>#}
{#        <script src="{% static '/js/notify.js' %}"></script>#}

{#        {% csrf_token %}#}
{#        <script src="{% static '/js/tickets_ua/station.js' %}"></script>#}
{#        <script src="{% static '/js/tickets_ua/checker.js' %}"></script>#}

    {% endif %}
{% endblock %}