apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.accounts.views import api
from apps.accounts.views.login import CustomLoginView
from apps.accounts.views.telegram_view import link_unlink_telegram

app_name = "accounts"
urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", api.SignUpView.as_view(), name="signup"),
    path("link_unlink_telegram/", link_unlink_telegram, name="link_unlink_telegram"),
    path("confirm-email/<str:uid>/<str:token>/", api.ConfirmEmailCompleteView.as_view(), name="confirm_email"),
]

apps/hotline_ua/urls.py
from django.urls import path

from apps.hotline_ua.views import api
from apps.hotline_ua.views.checker import CheckerListView

app_name = "hotline_ua"
urlpatterns = [
    path("", CheckerListView.as_view(), name="index"),

    path("api/category/", api.CategoryCreateAPIView.as_view(), name="api-category"),
    path("api/filter/", api.FilterCreateAPIView.as_view(), name="api-filter"),
    path("api/checker/", api.CheckerCreateAPIView.as_view(), name="api-checker"),
    path("api/checker/<int:pk>/", api.HotlineUaCheckerUpdateAPIView.as_view(), name='api-update-checker'),
]

apps/tickets_ua/urls.py
from django.urls import path

from apps.tickets_ua.views import api
from apps.tickets_ua.views.checker import CheckerListView

app_name = "tickets_ua"
urlpatterns = [
    path("", CheckerListView.as_view(), name="index"),

    path("api/station/", api.StationCreateAPIView.as_view(), name="api-station"),
    path("api/checker/", api.CheckerCreateAPIView.as_view(), name="api-checker"),
    path("api/checker/<int:pk>/", api.CheckerUpdateAPIView.as_view(), name='api-update-checker'),
]

apps/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.views import index, telegram, feedback, redirect_to_index_page, additional_settings, change_max_query_number, \
    change_vip_users_update_period, change_regular_users_update_period

urlpatterns = [
    path("", index, name="index"),
    path("", include('apps.tbot_base.urls')),  # include webhook url
    path("telegram/", telegram, name="telegram"),
    path("feedback/", feedback, name="feedback"),
    path("settings/", additional_settings, name="settings"),
    path("change_max_query_number/", change_max_query_number, name="change_max_query_number"),
    path("change_regular_users_update_period/", change_regular_users_update_period,
         name="change_regular_users_update_period"),
    path("change_vip_users_update_period/", change_vip_users_update_period, name="change_vip_users_update_period"),

    path('i18n/', include('django.conf.urls.i18n')),

    path("uz_ticket/", include('apps.uz_ticket_checker.urls'), name="uz_ticket_checker"),
    path("tickets_ua/", include('apps.tickets_ua.urls'), name="tickets_ua"),
    path("hotline_ua/", include('apps.hotline_ua.urls'), name="hotline_ua"),

    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('apps.accounts.urls'), name="accounts"),

    path('oauth2/inactive/', redirect_to_index_page),
    path('oauth2/', include('allauth.urls')),
    # path('oauth2/', include('allauth.socialaccount.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

apps/uz_ticket_checker/urls.py
from django.urls import path

from apps.uz_ticket_checker.views.checker_view import checker_add, checkers_view, checker_delete, \
    checker_change_is_active
from apps.uz_ticket_checker.views.stations_view import StationsListView, stations_update
from apps.uz_ticket_checker.views.ticket_search_view import search_ticket_view, get_search_results

app_name = "uz_ticket_checker_app"
urlpatterns = [
    path("", search_ticket_view, name="search_results"),
    path("execute_search_task/", get_search_results, name="execute_task"),
    path("checker/", checkers_view, name="checker"),
    path("checker/add/", checker_add, name="checker_add"),
    path("checker/delete/<int:pk>/", checker_delete, name="checker_delete"),
    path("checker/change_is_active/<int:pk>/", checker_change_is_active, name="checker_change_is_active"),
    path("stations/", StationsListView.as_view(), name="stations"),
    path("stations/update/", stations_update, name="stations_update"),
]

apps/common/views/base.py
from django.contrib import messages
from django.shortcuts import redirect, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic.list import BaseListView

from apps.task_manager.models import SessionTaskManager


class BaseCheckerListView(BaseListView):
    model_class = None
    template_name = None
    context_object_name = None
    checker_type = None

    def get_queryset(self):
        user = self.request.user
        return self.model_class.objects.filter(
            param_type__checker_task_parameters__user_id=user.id,
            param_type__checker_task_parameters__is_delete=False,
        )

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            messages.warning(self.request, _('Invalid access. Please log in.'))
            return redirect(reverse('index'))

        if not user.is_active:
            messages.warning(self.request, _('User blocked. You can logout.'))
            return redirect(reverse('index'))

        SessionTaskManager(request)

        return super().get(request, *args, **kwargs)

    class Meta:
        abstract = True

templates/fragments/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <title>Checker</title>
    <link href="{% static '/bootstrap/v5.3/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/bootstrap/v5.3/font/bootstrap-icons.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/dselect.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/daterangepicker.css' %}" rel="stylesheet">
    <link href="{% static '/css/rSlider.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static '/jquery/3.7.1/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/bootstrap/v5.3/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/color-modes.js' %}"></script>
</head>
<body class="d-flex flex-column min-vh-100 bg-body-tertiary">

<div class="container-fluid sticky-top mb-2">
    {% include "fragments/navigation.html" %}
</div>

<main class="container-fluid" id="main">
    {% include "fragments/notify.html" %}
    {% block main %} {% endblock %}
</main>

</body>
{% include "fragments/footer.html" %}
{% block extra_scripts %} {% endblock %}
</html>

templates/fragments/color-modes.html
{% load i18n %}
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (dark)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#moon-stars-fill"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                <span>{% translate "Light" %}</span>
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="dark"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                <span>{% translate "Dark" %}</span>
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                <span>{% translate "Auto" %}</span>
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

templates/fragments/footer.html
{% load i18n %}
<div class="container mt-auto">
    <footer class="py-3 my-4">
        {% include "fragments/color-modes.html" %}
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">{% translate "Main" %}</a></li>
            <li class="nav-item"><a href="{% url 'schema' %}" class="nav-link px-2 text-body-secondary">API {% translate "schema " %}</a></li>
            <li class="nav-item"><a href="/feedback/" class="nav-link px-2 text-body-secondary">Feedback</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2024 GeekHub, Python. All rights reserved.</p>
    </footer>
</div>

templates/fragments/navigation.html
{% load i18n %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">{% translate "Main" %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">API </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'swagger' %}">Swagger UI</a></li>
                        <li><a class="dropdown-item" href="{% url 'redoc' %}">Redoc</a></li>
                    </ul>
                <li>
                    <hr class="dropdown-divider">
                </li>
            
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets_ua:index' %}">Tickets UA</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hotline_ua:index' %}">Hotline UA</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'uz_ticket_checker_app:search_results' %}">UZ tickets Search</a>
                </li>
            </ul>

            <div class="d-flex justify-content-center pe-4">
                <ul class="navbar-nav me-auto mb-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle fw-bold mx-2" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">{{ user.email }} </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <form method="post" action="{% url 'accounts:logout' %}?next={{ request.path }}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn">&nbsp;{% translate "Logout" %} 
                                            <i class="bi bi-box-arrow-left"></i></button>
                                    </form>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'accounts:link_unlink_telegram' %}">
                                    {% if request.user.personal_setting.telegram_user_id > 0 %}
                                        Unlink Telegram
                                    {% else %}
                                        Link Telegram
                                    {% endif %}
                                </a></li>
                                {% if request.user.is_superuser %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="/admin">{% translate "Administrator panel" %}</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item"
                                           href="/uz_ticket/stations">{% translate "Railway Stations list" %}</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item"
                                           href="/settings">{% translate "Additional settings" %}</a></li>
                                {% endif %}
                            </ul>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active me-3"
                               href="{% url 'accounts:login' %}">{% translate "Login" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active me-3"
                               href="{% url 'accounts:signup' %}">{% translate "Signup" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>


            <div class="d-flex pe-4">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <div class=" d-flex">
                            <a class="nav-link" title="{% translate "user checkers count" %}" id="checker-count">
                                {{ request.session.session_key.counter_key.user_count }}
                            </a>
                            <a class="navbar-text">
                                |
                            </a>
                            <a class="nav-link" title="{% translate "max user checkers count" %}">
                                {% if request.session.session_key.counter_key.max_count %}
                                    {{ request.session.session_key.counter_key.max_count }}
                                {% else %}
                                    {% if request.user.is_authenticated %}
                                        {% translate "max" %}
                                    {% else %}
                                        0
                                    {% endif %}
                                {% endif %}
                                {% if request.user.is_superuser %}
                                    <a class="navbar-text"> | </a>
                                    <a class="nav-link" title="{% translate "all checkers count" %}" id="checker-count">
                                        {{ request.session.session_key.counter_key.all_count }}
                                    </a>
                                {% endif %}
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-lg-0">
                    <li class="nav-item">
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <input type="hidden" name="language" value="en"/>
                            <input class="nav-link text-light" type="submit" value="EN">
                        </form>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <input type="hidden" name="language" value="uk"/>
                            <input class="nav-link text-light" type="submit" value="UA">
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            const currentPageUrl = window.location.href;
            $('.nav-link').each(function () {
                const menuItemUrl = $(this).attr('href');
                if (currentPageUrl.includes(menuItemUrl)) {
                    $(this).addClass('text-primary active');
                } else {
                    $(this).removeClass('text-primary')
                }
            });
        });
    </script>
</nav>

templates/fragments/notify.html
{% load i18n %}
<div class="row my-5 fixed-top justify-content-center" id="errorMessages">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == 30 or message.level == 40 %}
                <div class="alert alert-warning alert-dismissible fade show w-75" role="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                         class="bi bi-x-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                    </svg>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

<div class="row my-5 fixed-top justify-content-center" id="infoMessages">
    {% if messages %}
        {% for message in messages %}
            {% if message.level < 30 %}
                <div class="alert alert-info alert-dismissible fade show w-75" role="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                         class="bi bi-info-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                    </svg>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

{% if request.GET.message %}
    <div class="row my-5 fixed-top justify-content-center" id="infoMessages">
        <div class="alert alert-info alert-dismissible fade show w-75" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                 class="bi bi-info-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
            </svg>
            {% if request.GET.message == 'Registration success' %}
                {% translate "Registration success. Please login." %}
            {% else %}    
                {{ request.GET.message }}
            {% endif %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
{% endif %}

<div class="toast-container position-fixed bottom-0 end-0 m-1 p-2">
    <div id="infoToast" class="toast text-white bg-success border-0" style="z-index: 11" role="alert"
         aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="textToast"></div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                    aria-label="Close"></button>
        </div>
    </div>
</div>