apps/hotline_ua/urls.py
from django.urls import path

from apps.hotline_ua.views import api
from apps.hotline_ua.views.checker import CheckerListView

app_name = "hotline_ua"
urlpatterns = [
    path("", CheckerListView.as_view(), name="index"),

    path("api/category/", api.CategoryCreateAPIView.as_view(), name="api-category"),
    path("api/filter/", api.FilterCreateAPIView.as_view(), name="api-filter"),
    path("api/checker/", api.CheckerCreateAPIView.as_view(), name="api-checker"),
    path("api/checker/<int:pk>/", api.HotlineUaCheckerUpdateAPIView.as_view(), name='api-update-checker'),
]

apps/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.views import index, telegram, feedback, redirect_to_index_page, additional_settings, change_max_query_number, \
    change_vip_users_update_period, change_regular_users_update_period

urlpatterns = [
    path("", index, name="index"),
    path("", include('apps.tbot_base.urls')),  # include webhook url
    path("telegram/", telegram, name="telegram"),
    path("feedback/", feedback, name="feedback"),
    path("settings/", additional_settings, name="settings"),
    path("change_max_query_number/", change_max_query_number, name="change_max_query_number"),
    path("change_regular_users_update_period/", change_regular_users_update_period,
         name="change_regular_users_update_period"),
    path("change_vip_users_update_period/", change_vip_users_update_period, name="change_vip_users_update_period"),

    path('i18n/', include('django.conf.urls.i18n')),

    path("uz_ticket/", include('apps.uz_ticket_checker.urls'), name="uz_ticket_checker"),
    path("tickets_ua/", include('apps.tickets_ua.urls'), name="tickets_ua"),
    path("hotline_ua/", include('apps.hotline_ua.urls'), name="hotline_ua"),

    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('apps.accounts.urls'), name="accounts"),

    path('oauth2/inactive/', redirect_to_index_page),
    path('oauth2/', include('allauth.urls')),
    # path('oauth2/', include('allauth.socialaccount.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

apps/hotline_ua/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import BaseParameter
from apps.common import TimeStampedMixin
from apps.common.models import ActiveStateMixin, AvailableStateMixin
from apps.hotline_ua.enums.filter import FilterType
from apps.hotline_ua.managers import CategoryManager, FilterManager


class Category(TimeStampedMixin, models.Model):
    objects = CategoryManager()

    code = models.IntegerField(_('code'), unique=True)
    title = models.CharField(_('title'), max_length=100, blank=False)
    url = models.CharField(_('url'), max_length=255, blank=False)

    path = models.CharField(_('token'), max_length=100, null=True, blank=True, )

    is_link = models.BooleanField(_('link'), default=False)
    is_active = models.BooleanField(_('active'), default=True)

    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        default=None,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")


class FilterTypeChoices(models.TextChoices):
    BRAND = FilterType.BRAND.value, _(FilterType.BRAND.value)
    LINK = FilterType.LINK.value, _(FilterType.LINK.value)
    SHOP = FilterType.SHOP.value, _(FilterType.SHOP.value)
    TEXT = FilterType.TEXT.value, _(FilterType.TEXT.value)
    MAX_PRICE = FilterType.MAX.value, _(FilterType.MAX.value)
    MIN_PRICE = FilterType.MIN.value, _(FilterType.MIN.value)


class Filter(models.Model):
    objects = FilterManager()
    type_choices_class = FilterTypeChoices

    code = models.IntegerField(_('code'))
    title = models.CharField(_('title'), max_length=100, blank=False)

    type_name = models.CharField(
        _('type'),
        max_length=20,
        blank=False,
        choices=type_choices_class.choices,
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        related_name='filters'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("filter")
        verbose_name_plural = _("filters")


class BaseSearchParameter(TimeStampedMixin, ActiveStateMixin, AvailableStateMixin, models.Model):
    filter_class = Filter

    param_type = models.OneToOneField(
        BaseParameter,
        parent_link=True,
        on_delete=models.CASCADE,
        related_name='hotline_ua_search_parameters'
    )

    filters = models.ManyToManyField(
        filter_class,
        related_name='search_parameters',
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        related_name='search_parameters'
    )

    class Meta:
        verbose_name = _("search_parameter")
        verbose_name_plural = _("search parameters")

apps/hotline_ua/views.py
from django.shortcuts import render

# Create your views here.

apps/hotline_ua/views/checker.py
from django.views.generic import ListView

from apps.common.views import BaseCheckerListView
from apps.common.enums.checker_name import CheckerTypeName
from apps.hotline_ua.models import BaseSearchParameter


class CheckerListView(BaseCheckerListView, ListView):
    model_class = BaseSearchParameter
    template_name = 'hotline_ua/index.html'
    context_object_name = 'checkers'
    checker_type = CheckerTypeName.HOTLINE_UA

templates/hotline_ua/index.html
{% extends 'fragments/base.html' %}
{% load i18n %}
{% load static %}

{% block main %}
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="my-3 p-3 bg-body rounded shadow-sm">
                <h3 class="pb-2">{% translate "Generated new checkers" %}:</h3>
                <div class="bg-body rounded shadow-sm py-3">
                    <form class="row g-4 p-3" id="createCheckerForm">
                        <div class="col-md-6 col-sm-12">
                            <div class="col-auto">
                                <label for="search-category" class="form-label ms-2">{% translate "Category" %}</label>
                                <input type="text" class="form-control" name="category" id="search-category"
                                       data-path="" placeholder="{% translate "e.g." %} Холодильники...">
                                <ul id="search-category-results"
                                    class="position-absolute text-bg-secondary pe-2 z-3"></ul>
                            </div>

                            <div class="col-auto pt-4">
                                <label for="search-category"
                                       class="form-label ms-2">{% translate "Base filters" %}</label>
                                <div>
                                    <select class="form-select" name="base-filter" id="dselect-base" aria-label="">
                                    </select>
                                </div>
                            </div>
                            <div class="col-auto">
                                <label class="form-label ms-2"></label>
                                <button class="btn btn-primary mt-2 form-control CreateCheckerBtn">{% translate "Generated" %}</button>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title text-secondary ">{% translate "Search" %}</h5>
                                    <input type="text" class="form-control" name="text" id="search-text"
                                           placeholder="{% translate "text" %}..." aria-label="">
                                </div>
                                <div class="px-3"
                                     title="{% translate "e.g. 50 000 and more" %}">
                                    <h5 class="card-title text-secondary pt-3">
                                        {% translate "Price range" %}
                                    </h5>
                                    <div class="pt-3 pb-1 ms-2">
                                        <div class="">
                                            <div class="pt-4 px-4">
                                                <input type="text" name="rangePrice" id="rangePrice" aria-label=""/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="px-0 progress " role="progressbar" aria-label="Animated load"
                             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                            <div id="load-progressbar" class="progress-bar progress-bar-striped progress-bar-animated"
                                 hidden="hidden" style="width: 100%"></div>
                        </div>
                        <div class=" col-xs-12 col-sm-12">
                            <div class="card h-100">
                                <div class="card-body">
                                    <div>
                                        <h5 class="card-title text-secondary ">{% translate "Others filters" %}</h5>
                                        <div>
                                            <label for="dselect-brand"
                                                   class="form-label ps-2 text-secondary">{% translate "brand" %}</label>
                                            <select class="form-select" name="brand" id="dselect-brand">
                                            </select>
                                        </div>
                                        <div class="pt-2">
                                            <label for="dselect-shop"
                                                   class="form-label ps-2 text-secondary">{% translate "shop" %}</label>
                                            <select class="form-select" name="shop" id="dselect-shop">
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="my-3 p-3 bg-body rounded shadow-sm">
                <h3 class="pb-2"> {% translate "Yours checkers" %}:</h3>
                <div class="bg-body rounded shadow-sm">
                    <table class="table">
                        <thead>
                        <tr class="text-center">
                            <th class="col-auto text-primary-emphasis"> {% translate "category" %}</th>
                            <th class="col-5 text-primary-emphasis"> {% translate "filters" %}</th>
                            <th class="col-1 text-primary-emphasis"> {% translate "active" %}</th>
                            <th class="col-auto text-primary-emphasis"> {% translate "checked" %}</th>
                            <th class="col-1"></th>
                        </tr>
                        </thead>


                        <tbody id="checkersBodyTable">
                        {% if checkers %}
                            {% for checker in checkers %}
                                <tr>
                                    <td>
                                        <small>
                                            {% if checker.category %}
                                                {{ checker.category.title }}
                                            {% else %}
                                                <small class="text-secondary text-opacity-50">
                                                    {% translate "search product title..." %}
                                                </small>
                                            {% endif %}
                                        </small>
                                    </td>
                                    <td>
                                        {% if checker.filters %}
                                            {% for filter in checker.filters.all %}
                                                {% if filter.type_name == "min" or filter.type_name == "max" %}
                                                    <small title="{{ filter.type_name }}">[{{ filter.code }}],</small>
                                                {% else %}
                                                    <small title="{{ filter.type_name }}">{{ filter.title }},</small>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input activeCheckerButton" type="checkbox"
                                                   value="{{ checker.is_active }}" aria-label="checker_active_state"
                                                   data-checker_id="{{ checker.id }}"
                                                    {% if checker.is_active %} checked {% endif %}>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <div>
                                            <small class="text-secondary text-opacity-50"
                                                   title="{% translate "last checked" %}">
                                                {{ checker.updated_at|date:"Y-m-d H:i" }}
                                            </small>

                                            {% if checker.is_available %}
                                                <i class="p-2 text-success fs-5 bi bi-check2-all"
                                                   title="{% translate "available" %}"></i>
                                            {% else %}
                                                <i class="p-2 text-danger bi bi-ban"
                                                   title="{% translate "not available" %}"></i>
                                            {% endif %}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="input-group d-flex justify-content-center">
                                            <button title="{% translate "trash" %}"
                                                    class="nav-link bi bi-trash mx-1 deleteCheckerButton"
                                                    data-checker_id="{{ checker.id }}">
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <script src="{% static '/js/rSlider.min.js' %}"></script>
        <script>
            const maxRange = 50000;
            const priceSlider = new rSlider({
                target: '#rangePrice',
                values: {min: 0, max: maxRange},
                step: 100,
                range: true,
                tooltip: true,
                scale: false,
                labels: false,
                width: '210px',
                {#disabled: true,#}
                {#minWidth:'300px'#}
                {#set: [0, 50000]#}
            });
            console.log(priceSlider.getValue())
        </script>

        <script src="{% static '/js/dselect.min.js' %}"></script>
        <script>
            const config = {
                search: true,
                {#creatable: true,#}
                clearable: true,
                maxHeight: '360px',
                size: '', // Can be "sm" or "lg". Default ''
            }
        </script>
        <script>
            window.CategoryUrl = "{% url 'hotline_ua:api-category' %}"
            window.FilterUrl = "{% url 'hotline_ua:api-filter' %}"
            window.ChekerUrl = "{% url 'hotline_ua:api-checker' %}"
        </script>

        <script src="{% static '/js/calc.js' %}"></script>
        <script src="{% static '/js/ajax.js' %}"></script>
        <script src="{% static '/js/notify.js' %}"></script>


        {% csrf_token %}
        <script src="{% static '/js/hotline_ua/category.js' %}"></script>
        <script src="{% static '/js/hotline_ua/filter.js' %}"></script>
        <script src="{% static '/js/hotline_ua/checker.js' %}"></script>
    {% endif %}
{% endblock %}