apps/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.views import index, telegram, feedback, redirect_to_index_page, additional_settings, change_max_query_number, \
    change_vip_users_update_period, change_regular_users_update_period

urlpatterns = [
    path("", index, name="index"),
    path("", include('apps.tbot_base.urls')),  # include webhook url
    path("telegram/", telegram, name="telegram"),
    path("feedback/", feedback, name="feedback"),
    path("settings/", additional_settings, name="settings"),
    path("change_max_query_number/", change_max_query_number, name="change_max_query_number"),
    path("change_regular_users_update_period/", change_regular_users_update_period,
         name="change_regular_users_update_period"),
    path("change_vip_users_update_period/", change_vip_users_update_period, name="change_vip_users_update_period"),

    path('i18n/', include('django.conf.urls.i18n')),

    path("uz_ticket/", include('apps.uz_ticket_checker.urls'), name="uz_ticket_checker"),
    path("tickets_ua/", include('apps.tickets_ua.urls'), name="tickets_ua"),
    path("hotline_ua/", include('apps.hotline_ua.urls'), name="hotline_ua"),

    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('apps.accounts.urls'), name="accounts"),

    path('oauth2/inactive/', redirect_to_index_page),
    path('oauth2/', include('allauth.urls')),
    # path('oauth2/', include('allauth.socialaccount.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

apps/uz_ticket_checker/urls.py
from django.urls import path

from apps.uz_ticket_checker.views.checker_view import checker_add, checkers_view, checker_delete, \
    checker_change_is_active
from apps.uz_ticket_checker.views.stations_view import StationsListView, stations_update
from apps.uz_ticket_checker.views.ticket_search_view import search_ticket_view, get_search_results

app_name = "uz_ticket_checker_app"
urlpatterns = [
    path("", search_ticket_view, name="search_results"),
    path("execute_search_task/", get_search_results, name="execute_task"),
    path("checker/", checkers_view, name="checker"),
    path("checker/add/", checker_add, name="checker_add"),
    path("checker/delete/<int:pk>/", checker_delete, name="checker_delete"),
    path("checker/change_is_active/<int:pk>/", checker_change_is_active, name="checker_change_is_active"),
    path("stations/", StationsListView.as_view(), name="stations"),
    path("stations/update/", stations_update, name="stations_update"),
]

apps/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_info = forms.CharField(label='Контактні дані відправника', max_length=200)
    subject = forms.CharField(label='Тема повідомлення', max_length=200)
    description = forms.CharField(label='Опис', widget=forms.Textarea)

    def clean(self):
        cleaned_data = super().clean()
        contact_info = cleaned_data.get('contact_info')
        subject = cleaned_data.get('subject')
        description = cleaned_data.get('description')

        if not contact_info or not subject or not description:
            raise forms.ValidationError("Всі поля мають бути заповнені")


class MaxQueryNumberForm(forms.Form):
    max_query_number = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        max_query_number = cleaned_data.get('max_query_number')

        if not max_query_number:
            raise forms.ValidationError("Поле має бути заповнене")


class RegularUsersUpdatePeriodForm(forms.Form):
    regular_users_update_period = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        regular_users_update_period = cleaned_data.get('regular_users_update_period')

        if not regular_users_update_period:
            raise forms.ValidationError("Поле має бути заповнене")


class VipUsersUpdatePeriodForm(forms.Form):
    vip_users_update_period = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        vip_users_update_period = cleaned_data.get('vip_users_update_period')

        if not vip_users_update_period:
            raise forms.ValidationError("Поле має бути заповнене")

templates/feedback.html
{% extends 'fragments/base.html' %}
{% load static %}

{% block main %}
    <style>
        .form-group {
            display: flex;
            align-items: center;
            margin-bottom: 15px; /* Змінено відступ між рядками */
        }

        .form-label {
            width: 250px; /* Збільшено ширину для заголовків полів */
            text-align: right; /* Центрування тексту */
            margin-right: 15px; /* Змінено відступ від правого краю */
        }

        .form-field {
            flex: 1;
        }

        .submit-btn {
            margin-left: 265px; /* Перемістити кнопку відправлення вправо */
        }

        .form-control.form-field.descr {
            height: 300px; /* Встановлюємо висоту 200px */
        }
    </style>

    <div class="container">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h3 class="pb-2" align="center">Форма зворотнього зв'язку</h3>
            <form method="post" action="{% url 'feedback' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_contact_info" class="form-label">Контактні дані відправника:</label>
                    <input type="text" class="form-control form-field" id="id_contact_info" name="contact_info">
                </div>
                <div class="form-group">
                    <label for="id_subject" class="form-label">Тема повідомлення:</label>
                    <input type="text" class="form-control form-field" id="id_subject" name="subject">
                </div>
                <div class="form-group">
                    <label for="id_description" class="form-label">Опис:</label>
                    <textarea class="form-control form-field descr" id="id_description" name="description"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn">Відправити</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'fragments/base.html' %}
{% load static %}

{% block main %}
<style>
    #about_project {
        font-size: 18px; /* Змініть значення, якщо потрібно зробити шрифт ще більшим */
        text-align: justify; /* Вирівнювання тексту по ширині */
    }
</style>
<div class="container-fluid" id="information_block" data-auth="NotAuthenticated">
    <div class="container">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h1 class="d-flex justify-content-center mt-4">ПРО ПРОЄКТ</h1>
            <div id="about_project">
                <p><b>Checker</b> – це Web-платформа для здійснення періодичних запитів та аналізу інформації
                    визначеного напряму
                    та характеру з подальшим сповіщенням користувачів, якщо отримана інформація відповідає заданим
                    очікуваним критеріям користувача.
                    На даний момент на платформі реалізовано 3 сервіси:
                </p>
                <ol>
                    <li>
                        <a href="/uz_ticket/">Сервіс перевірки наявності залізничних квитків Укрзалізниці</a>
                        (використовуються дані <a href="https://proizd.ua/">proizd.ua</a>) з
                        подальшим надсиланням сповіщень користувачу через <a href="https://t.me/CheckerGeekHubBot">телеграм-бот</a>
                        інформації щодо наявних місць на
                        знайдені за заданими параметрами потягів (в розрізі дат, потягів, типів вагонів, типів місць).
                        Також
                        доступна можливість здійснювати пошук наявних квитків безпосередньо на даний момент й за потреби
                        перейти на proizd.ua для їх купівлі.
                    </li>
                    <li>
                        <a href="/tickets_ua/">Сервіс перевірки залізничних та автобусних квитків</a> (використовуються
                        дані <a href="https://tickets.ua/">tickets.ua</a>) з подальшим
                        надсиланням сповіщень користувачу загальної інформації про наявність квитків та їх кількість.
                    </li>
                    <li>
                        <a href="/hotline_ua/">Сервіс перевірки наявності товарів</a> (використовуються дані <a
                            href="https://hotline.ua/">hotline.ua</a>) з подальшим надсиланням
                        сповіщень користувачу інформації, щодо їх наявності, що відповідають заданим параметрам (в
                        розрізі категорій, підкатегорій, тексту в назві товару, діапазону цін, брендів та магазинів).
                    </li>
                </ol>
                <p>Платформу створено в рамках фінальної роботи проєкту <a href="https://geekhub.ck.ua/">GeekHub</a>
                    випускниками 13 сезону курсів Python та Quality Assurance.</p>
                <p>Ви можете вказати свої <a href="/feedback/">пропозиції</a>, щодо покращення роботи платформи, які
                    будуть надіслані адміністрації проєкту.</p>
            </div>


        </div>
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h1 class="d-flex justify-content-center mt-4">ПРО АВТОРІВ</h1>
            <div id="authors">
                <br>
                <br>
                <h3 class="mb-2">1. Автор ідеї проєкту та Python-розробник <b>Ковальчук Володимир</b></h3>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-linkedin fs-5 pe-2"></i>
                    <a href="https://www.linkedin.com/in/volodymyr-kovalchuk-5b211010a/" target="_blank">LinkedIn</a>
                </p>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-telegram fs-5 pe-2"></i>
                    <a href="https://t.me/slengpack" target="_blank">Telegram</a>
                </p>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-envelope-at-fill fs-5 pe-2"></i>
                    <a href="mailto:slengpack@gmail.com" target="_blank">Email</a>
                </p>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-github fs-5 pe-2"></i>
                    <a href="https://github.com/vkovalchuk-91" target="_blank">GitHub</a>
                </p>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-facebook fs-5 pe-2"></i>
                    <a href="https://www.facebook.com/slengpack" target="_blank">Facebook</a>
                </p>
                <p class="d-flex align-items-center">
                    <i class="bi bi-geo-alt-fill fs-5 pe-2"></i>
                    <a class="nav-link text-secondary">Київ, Україна</a>
                </p>
                <h3 class="mb-2">2. Python-розробник <b>Климчук Андрій</b></h3>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-linkedin fs-5 pe-2"></i>
                    <a href="https://www.linkedin.com/in/andrii-klymchuk/" target="_blank">LinkedIn</a>
                </p>
                <p class="d-flex align-items-center">
                    <i class="bi bi-geo-alt-fill fs-5 pe-2"></i>
                    <a class="nav-link text-secondary">Черкаси, Україна</a>
                </p>
                <h3 class="mb-2">3. QA-manual інженер <b>Хавроненко Ольга</b></h3>
                <p class="d-flex align-items-center m-0">
                    <i class="bi bi-linkedin fs-5 pe-2"></i>
                    <a href="https://www.linkedin.com/in/%D0%BElha-khavronenko-1b8146266/" target="_blank">LinkedIn</a>
                </p>
                <p class="d-flex align-items-center">
                    <i class="bi bi-geo-alt-fill fs-5 pe-2"></i>
                    <a class="nav-link text-secondary">Черкаси, Україна</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/settings.html
{% extends 'fragments/base.html' %}
{% load static %}

{% block main %}
    <style>
        .form-group {
            display: flex;
            align-items: center;
            margin-bottom: 15px; /* Змінено відступ між рядками */
        }

        .form-label {
            width: 250px; /* Збільшено ширину для заголовків полів */
            text-align: right; /* Центрування тексту */
            margin-right: 15px; /* Змінено відступ від правого краю */
        }

        .form-field {
            width: 70px;
        }

        .submit-btn {
            margin-left: 265px; /* Перемістити кнопку відправлення вправо */
        }

        .note {
            margin-left: 265px; /* Перемістити кнопку відправлення вправо */
            font-style: italic; /* Зробити текст курсивним */
            color: #dc3545; /* Змінити колір тексту на сірий */
        }
    </style>

    <div class="container">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h3 class="pb-2" align="center">Додаткові налаштування</h3>
            <form method="post" action="{% url 'change_max_query_number' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="max_query_number" class="form-label">Змінити максимальну кількість checker-ів для REGULAR
                        користувачів:</label>
                    <input type="number" class="form-control form-field" id="max_query_number" name="max_query_number"
                           min="1" max="60" value="{{ max_query_number }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn">Оновити</button>
                </div>
            </form>
            <div class="note">* Персонально для кожного користувача кількість cheker-ів можна оновити на <a
                    style="color: blue; text-decoration: underline;" href="/admin">панелі адміністратора</a></div>

            <br><br>
            <form method="post" action="{% url 'change_regular_users_update_period' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="regular_users_update_period" class="form-label">Змінити час через який будуть
                        повторюватися checker запити для REGULAR
                        користувачів (хвилин):</label>
                    <input type="number" class="form-control form-field" id="regular_users_update_period"
                           name="regular_users_update_period"
                           min="1" max="60" value="{{ regular_users_update_period }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn">Оновити</button>
                </div>
            </form>
            <div class="note">* Персонально для кожного користувача час через який будуть повторюватися cheker-запити
                можна оновити на
                <a style="color: blue; text-decoration: underline;" class="dropdown-item" href="/admin">панелі
                    адміністратора</a></div>

            <br><br>
            <form method="post" action="{% url 'change_vip_users_update_period' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="vip_users_update_period" class="form-label">Змінити час через який будуть
                        повторюватися checker запити для VIP
                        користувачів (хвилин):</label>
                    <input type="number" class="form-control form-field" id="vip_users_update_period"
                           name="vip_users_update_period"
                           min="1" max="60" value="{{ vip_users_update_period }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn">Оновити</button>
                </div>
            </form>
            <div class="note">* Персонально для кожного користувача час через який будуть повторюватися cheker-запити
                можна оновити на
                <a style="color: blue; text-decoration: underline;" class="dropdown-item" href="/admin">панелі
                    адміністратора</a></div>

            <br><br>
            <form method="post" action="{% url 'uz_ticket_checker_app:stations_update' %}">
                {% csrf_token %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn">Оновити перелік станцій для сервісу "UZ
                        tickets Search"
                    </button>

                </div>
            </form>
            <div class="note">* Будьте обережні, оновлення виконуватимуться кілька годин!!!</div>
        </div>
    </div>
{% endblock %}